name: "coverage"
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - uses: cheyer/jest-coverage-report-action@c026e98ae079f4b0b027252c8e957f5ebd420610
        with:
          test-script: npm run coverage
          skip-step: install
